#!/bin/bash
set -e

#Add setup RES lab
echo "Setup for the RES lab!!"
echo "Static App 1 URL: $STATIC_APP1"
echo "Static App 2 URL: $STATIC_APP2"
echo "Static App 3 URL: $STATIC_APP3"
echo "Dynamic App 1 URL: $DYNAMIC_APP1"
echo "Dynamic App 2 URL: $DYNAMIC_APP2"
echo "Dynamic App 3 URL: $DYNAMIC_APP3"

php /var/apache2/templates/config-template.php > /etc/apache2/sites-available/001-apache_reverse_proxy.conf

#Apache get grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

exec apache2ctl -DFOREGROUND

